version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      - TZ=America/Sao_Paulo
      - POSTGRES_DB=controle_ponto
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD="senha"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: .
    ports:
      - "3001:3001"
    environment:
      - TZ=America/Sao_Paulo
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=controle_ponto
      - DB_USER=root
      - DB_PASSWORD="senha"
    depends_on:
      - postgres
    networks:
      - app-network
    volumes:
      - /app/node_modules

  frontend:
    build:
      context: ../frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
