version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: controle_ponto
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Lourenco2002
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: .
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: controle_ponto
      DB_USER: root
      DB_PASSWORD: Lourenco2002
    depends_on:
      - postgres
    networks:
      - app-network
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
